version: '3'
services:
  drblistener:
    build:
        context: .
        dockerfile: discord_listener.dockerfile
    image: 'drblistener:latest'
    restart: always
  drbhandler:
    build:
        context: .
        dockerfile: message_handler.dockerfile
    image: 'drbhandler:latest'
    restart: always
  drbconeremover:
    build:
        context: .
        dockerfile: cone_remover.dockerfile
    image: 'drbconeremover:latest'
    restart: always
  drbwotupdater:
    build:
        context: .
        dockerfile: wot_updater.dockerfile
    image: 'drbwotupdater:latest'
    restart: always
  drbflasksite:
    build:
        context: .
        dockerfile: flask_site.dockerfile
    image: 'drbflasksite:latest'
    restart: always
    ports:
      - '8080:8080'
