version: '3'
services:
  drblistener:
    build:
        context: .
        dockerfile: discord_listener.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drblistener:latest'
    restart: always
  drbhandler:
    build:
        context: .
        dockerfile: message_handler.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbhandler:latest'
    restart: always
  drbconeremover:
    build:
        context: .
        dockerfile: cone_remover.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbconeremover:latest'
    restart: always
  drbwotupdater:
    build:
        context: .
        dockerfile: wot_updater.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbwotupdater:latest'
    restart: always
  drbflasksite:
    build:
        context: .
        dockerfile: flask_site.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbflasksite:latest'
    restart: always
    ports:
      - '8080:8080'
  drbcitadelcheck:
    build:
        context: .
        dockerfile: citadel_check.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbcitadelcheck:latest'
    restart: always
  drbstatchecker:
    build:
        context: .
        dockerfile: stat_checker.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbstatchecker:latest'
    restart: always
  drbtwitchchecker:
    build:
        context: .
        dockerfile: twitch_checker.dockerfile
    image: 'rddtdiscordbot.azurecr.io/drbtwitchchecker:latest'
    restart: always
