Start-Process 'docker' -NoNewWindow -ArgumentList "rmi drblistener:latest"
Start-Process 'docker' -NoNewWindow -ArgumentList "rmi drbhandler:latest"
Start-Process 'docker' -NoNewWindow -ArgumentList "rmi drbconeremover:latest"
Start-Process 'docker' -NoNewWindow -ArgumentList "rmi drbwotupdater:latest"
Start-Process 'docker' -NoNewWindow -ArgumentList "rmi dwbflasksite:latest"